### ISSUE TITLE
Error on import javafx control

### ISSUE THREAD

**Issue by f-lima** [jython/jython.github.io#8]
Copy the code below to test.py and run it

    from javafx.scene.control import TabPane
    print("Ok")

It returns an error saying:
> java.lang.ExceptionInInitializerError
> Caused by: java.lang.IllegalStateException: Toolkit not initialized

Complete Error report:

    Traceback (most recent call last):
    File "test.py", line 1, in <module>
        from javafx.scene.control import TabPane
    java.lang.ExceptionInInitializerError
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at org.python.core.Py.loadAndInitClass(Py.java:991)
    at org.python.core.Py.findClassInternal(Py.java:926)
    at org.python.core.Py.findClassEx(Py.java:977)
    at org.python.core.packagecache.SysPackageManager.findClass(SysPackageManager.java:133)
    at org.python.core.packagecache.PackageManager.findClass(PackageManager.java:33)
    at org.python.core.packagecache.SysPackageManager.findClass(SysPackageManager.java:122)
    at org.python.core.PyJavaPackage.__findattr_ex__(PyJavaPackage.java:134)
    at org.python.core.PyObject.__findattr__(PyObject.java:946)
    at org.python.core.imp.importFromAs(imp.java:1160)
    at org.python.core.imp.importFrom(imp.java:1132)
    at org.python.pycode._pyx0.f$0(test.py:3)
    at org.python.pycode._pyx0.call_function(test.py)
    at org.python.core.PyTableCode.call(PyTableCode.java:167)
    at org.python.core.PyCode.call(PyCode.java:18)
    at org.python.core.Py.runCode(Py.java:1386)
    at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
    at org.python.util.jython.run(jython.java:362)
    at org.python.util.jython.main(jython.java:142)
    Caused by: java.lang.IllegalStateException: Toolkit not initialized
    at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:273)
    at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:268)
    at com.sun.javafx.application.PlatformImpl.setPlatformUserAgentStylesheet(PlatformImpl.java:550)
    at com.sun.javafx.application.PlatformImpl.setDefaultPlatformUserAgentStylesheet(PlatformImpl.java:512)
    at javafx.scene.control.Control.<clinit>(Control.java:87)
    ... 20 more

    java.lang.ExceptionInInitializerError: java.lang.ExceptionInInitializerError

Something is happening at **import** command that is generating this error.
As you can see at code, I am just importing but not using the imported class.

Added: I just noticed that the same error occurs when I try import Control directly.
Appears that the error are in creation of this class and classes that have Control as parent class, for any reason. By the other side, try to import classes that have Pane as parent works, even having Pane  Control as his parent class. I don't know if this information helps.

Thanks for your help.

**Comment by adamburkegh** [comment]
Hi Fernando

It looks to me like this is because JavaFX does some static toolkit initialization, and assumes it always happens in a particular idiomatic way, that doesn't play well with other tools. This happens in class static initializers so is prone to ordering issues.

There is a good discussion of similar errors interoperating with Swing and in running pure Java unit tests here, found by googling for the Java exception:

https://stackoverflow.com/questions/11273773/javafx-2-1-toolkit-not-initialized

Using one of the solutions there, I was able to slightly extend your sample code, and include some of the other imports from the JavaFX hello world. This uses the jython latest.

```
from java.lang import Runnable
from com.sun.javafx.application import PlatformImpl

class R(Runnable):
    def run(self):
        None


PlatformImpl.startup(R())

from javafx.application import Application
from javafx.event import ActionEvent
from javafx.event import EventHandler
from javafx.scene import Scene;
from javafx.scene.control import Button
from javafx.scene.layout import StackPane
from javafx.stage import Stage

from javafx.scene.control import TabPane

print("Ok")
```

Calling PlatformImpl directly is a little hacky, but it basically just proves it isn't jython-specific but load-order specific especially when other run threads are involved. There are some other workarounds at that link and you can select one. Keep in mind that imports don't all need to come at the top in Python or Jython.

I guess Jython is invoking the class initializer at first import reference, per Python behaviour, rather than raw Java when the classloader would invoke the static initializer in more of a just in time fashion.

I'd suggest it's more of of a JavaFX quirk than a Jython bug, at any rate.
